// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pagination.Data;

#nullable disable

namespace Pagination.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20241128103658_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pagination.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RollNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("735aa94f-f552-46b1-b1b3-60134e48cdbb"),
                            Address = "Nagpur",
                            Name = "Shyam Kumavat",
                            RollNo = 23
                        },
                        new
                        {
                            Id = new Guid("7e7d3372-886f-45d0-8560-e4aaa79f603e"),
                            Address = "Mumbai",
                            Name = "Amit Kumar",
                            RollNo = 24
                        },
                        new
                        {
                            Id = new Guid("fab60bdf-0ad8-448c-b825-1d4cfabfe15a"),
                            Address = "Pune",
                            Name = "Priya Verma",
                            RollNo = 25
                        },
                        new
                        {
                            Id = new Guid("5d5cb106-099b-4430-870e-4c9ac3cf409b"),
                            Address = "Nagpur",
                            Name = "Neha Joshi",
                            RollNo = 26
                        },
                        new
                        {
                            Id = new Guid("c6f78ea8-284e-440f-98f7-b9d2adeaf4f9"),
                            Address = "Delhi",
                            Name = "Raj Patel",
                            RollNo = 27
                        },
                        new
                        {
                            Id = new Guid("4066d33e-4456-4d67-9bf3-20d010f04568"),
                            Address = "Chennai",
                            Name = "Ankit Singh",
                            RollNo = 28
                        },
                        new
                        {
                            Id = new Guid("61875e0d-ce14-4414-b0fb-a02f8d359c5b"),
                            Address = "Mumbai",
                            Name = "Ravi Sharma",
                            RollNo = 29
                        },
                        new
                        {
                            Id = new Guid("9a9b9f48-d7a4-4e26-a17a-c34df0fb7329"),
                            Address = "Pune",
                            Name = "Simran Kaur",
                            RollNo = 30
                        },
                        new
                        {
                            Id = new Guid("d78c4999-f37c-473a-ae40-e18f98460b78"),
                            Address = "Delhi",
                            Name = "Vikram Yadav",
                            RollNo = 31
                        },
                        new
                        {
                            Id = new Guid("cbc61512-63d0-4496-b1c7-7fd26fcc7496"),
                            Address = "Nagpur",
                            Name = "Aarti Agarwal",
                            RollNo = 32
                        },
                        new
                        {
                            Id = new Guid("e68a4628-f2fd-49f6-9adc-c3c93d772dc4"),
                            Address = "Chennai",
                            Name = "Manish Joshi",
                            RollNo = 33
                        },
                        new
                        {
                            Id = new Guid("e2a8d556-be88-4ada-9bde-d4b0663f81c0"),
                            Address = "Mumbai",
                            Name = "Tanvi Mehta",
                            RollNo = 34
                        },
                        new
                        {
                            Id = new Guid("317951a3-c8a0-4195-ae3f-0ec1e903995f"),
                            Address = "Pune",
                            Name = "Karan Deshmukh",
                            RollNo = 35
                        },
                        new
                        {
                            Id = new Guid("d0e1237f-f0fb-47ec-a214-ab2363d942e0"),
                            Address = "Nagpur",
                            Name = "Nikita Singh",
                            RollNo = 36
                        },
                        new
                        {
                            Id = new Guid("0821ca09-05eb-4833-aeb2-7274e9c6ab17"),
                            Address = "Delhi",
                            Name = "Pradeep Kumar",
                            RollNo = 37
                        },
                        new
                        {
                            Id = new Guid("2179d5d1-e7f5-432a-b359-d21ec501364f"),
                            Address = "Chennai",
                            Name = "Sakshi Sharma",
                            RollNo = 38
                        },
                        new
                        {
                            Id = new Guid("d588398b-cdba-456e-b6ab-4326f858962b"),
                            Address = "Mumbai",
                            Name = "Ritika Patel",
                            RollNo = 39
                        },
                        new
                        {
                            Id = new Guid("780f7946-abd4-4e75-a418-82dbfffb22e0"),
                            Address = "Pune",
                            Name = "Akhil Gupta",
                            RollNo = 40
                        },
                        new
                        {
                            Id = new Guid("933e736a-0869-4397-9f72-7a0a7ed4cf89"),
                            Address = "Nagpur",
                            Name = "Mehul Jain",
                            RollNo = 41
                        },
                        new
                        {
                            Id = new Guid("b7c6cbf1-05b6-4a97-b937-881b556f6437"),
                            Address = "Delhi",
                            Name = "Parul Sharma",
                            RollNo = 42
                        },
                        new
                        {
                            Id = new Guid("8f8baaad-fcba-4d67-8d39-5293fa26230b"),
                            Address = "Chennai",
                            Name = "Siddharth Thakur",
                            RollNo = 43
                        },
                        new
                        {
                            Id = new Guid("1a8e0a3e-c392-481e-b864-81b40954e37d"),
                            Address = "Mumbai",
                            Name = "Isha Gupta",
                            RollNo = 44
                        },
                        new
                        {
                            Id = new Guid("3baeedb1-f4ff-44af-8fc9-0d3ffbf25251"),
                            Address = "Pune",
                            Name = "Tarun Kumar",
                            RollNo = 45
                        },
                        new
                        {
                            Id = new Guid("83cfaa71-43b6-4581-89ef-b34ab5e5391c"),
                            Address = "Nagpur",
                            Name = "Kajal Verma",
                            RollNo = 46
                        },
                        new
                        {
                            Id = new Guid("ddf5d950-53ff-4ff3-9cc3-288c1d376c24"),
                            Address = "Delhi",
                            Name = "Devika Reddy",
                            RollNo = 47
                        },
                        new
                        {
                            Id = new Guid("e7be6cd2-213d-42a0-8c4b-d6a099c85610"),
                            Address = "Chennai",
                            Name = "Rohit Pandey",
                            RollNo = 48
                        },
                        new
                        {
                            Id = new Guid("c20442ac-3bdd-448b-980b-98720195ea1d"),
                            Address = "Mumbai",
                            Name = "Harshita Singh",
                            RollNo = 49
                        },
                        new
                        {
                            Id = new Guid("632add4d-887f-4670-b515-c0981530791c"),
                            Address = "Pune",
                            Name = "Sandeep Raghav",
                            RollNo = 50
                        },
                        new
                        {
                            Id = new Guid("f643d8a7-ab67-4f20-91bd-22f8685b758b"),
                            Address = "Nagpur",
                            Name = "Madhuri Gupta",
                            RollNo = 51
                        },
                        new
                        {
                            Id = new Guid("1e9f92c8-8f28-4060-b537-ba305b590acc"),
                            Address = "Delhi",
                            Name = "Pranav Joshi",
                            RollNo = 52
                        },
                        new
                        {
                            Id = new Guid("67938843-7fc9-4ca8-b598-77fc7707db5f"),
                            Address = "Chennai",
                            Name = "Gaurav Patil",
                            RollNo = 53
                        },
                        new
                        {
                            Id = new Guid("a3f7b737-4cd1-449e-9d0f-59ce12dc9fa9"),
                            Address = "Mumbai",
                            Name = "Sonali Verma",
                            RollNo = 54
                        },
                        new
                        {
                            Id = new Guid("e935ebc4-2726-446a-bb13-519257e2c696"),
                            Address = "Pune",
                            Name = "Tushar Yadav",
                            RollNo = 55
                        },
                        new
                        {
                            Id = new Guid("d2f83a45-ada4-4e55-adbd-568af2a0d406"),
                            Address = "Nagpur",
                            Name = "Pooja Mehta",
                            RollNo = 56
                        },
                        new
                        {
                            Id = new Guid("214979cb-d71d-4081-b693-10451df39fd1"),
                            Address = "Delhi",
                            Name = "Vishal Kumar",
                            RollNo = 57
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
