// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pagination.Data;

#nullable disable

namespace Pagination.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20241128103456_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pagination.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RollNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a210f44-758e-4865-a5e4-37cf05e12363"),
                            Address = "Nagpur",
                            Name = "Shyam Kumavat",
                            RollNo = 23
                        },
                        new
                        {
                            Id = new Guid("68cb2ae4-9e38-417e-a711-2edc3efc33f9"),
                            Address = "Mumbai",
                            Name = "Amit Kumar",
                            RollNo = 24
                        },
                        new
                        {
                            Id = new Guid("9e6943b4-abf4-4bec-8174-dc3ef98d1790"),
                            Address = "Pune",
                            Name = "Priya Verma",
                            RollNo = 25
                        },
                        new
                        {
                            Id = new Guid("cb33c27d-5d5d-4707-a9d0-eee1a16f7b30"),
                            Address = "Nagpur",
                            Name = "Neha Joshi",
                            RollNo = 26
                        },
                        new
                        {
                            Id = new Guid("a3c0dfad-35a7-4f2f-b99a-0493ffe2b463"),
                            Address = "Delhi",
                            Name = "Raj Patel",
                            RollNo = 27
                        },
                        new
                        {
                            Id = new Guid("47d44011-c793-4608-844e-9994494d902b"),
                            Address = "Chennai",
                            Name = "Ankit Singh",
                            RollNo = 28
                        },
                        new
                        {
                            Id = new Guid("43577e46-cc8d-426f-bdae-329803711200"),
                            Address = "Mumbai",
                            Name = "Ravi Sharma",
                            RollNo = 29
                        },
                        new
                        {
                            Id = new Guid("0f5d492e-b509-424e-b180-136f1697e52a"),
                            Address = "Pune",
                            Name = "Simran Kaur",
                            RollNo = 30
                        },
                        new
                        {
                            Id = new Guid("2af9af0b-a21e-4851-8cf7-a4d499e4a58d"),
                            Address = "Delhi",
                            Name = "Vikram Yadav",
                            RollNo = 31
                        },
                        new
                        {
                            Id = new Guid("47addbb1-5bd5-4269-9d44-abc31ac6e349"),
                            Address = "Nagpur",
                            Name = "Aarti Agarwal",
                            RollNo = 32
                        },
                        new
                        {
                            Id = new Guid("69a2eebe-03cc-47fe-a6f8-8cffdb0181a3"),
                            Address = "Chennai",
                            Name = "Manish Joshi",
                            RollNo = 33
                        },
                        new
                        {
                            Id = new Guid("1bbe8309-d595-4a5e-9327-31608556ed48"),
                            Address = "Mumbai",
                            Name = "Tanvi Mehta",
                            RollNo = 34
                        },
                        new
                        {
                            Id = new Guid("2f790e80-599f-4e8d-a5c3-cef319e15b02"),
                            Address = "Pune",
                            Name = "Karan Deshmukh",
                            RollNo = 35
                        },
                        new
                        {
                            Id = new Guid("3f0d2bb4-e762-4ed0-b133-732525154392"),
                            Address = "Nagpur",
                            Name = "Nikita Singh",
                            RollNo = 36
                        },
                        new
                        {
                            Id = new Guid("8c28ed92-ad9f-49b6-9d3a-b1a9cc92d9ee"),
                            Address = "Delhi",
                            Name = "Pradeep Kumar",
                            RollNo = 37
                        },
                        new
                        {
                            Id = new Guid("4bdea171-0bc8-4392-b02a-e1af563dc402"),
                            Address = "Chennai",
                            Name = "Sakshi Sharma",
                            RollNo = 38
                        },
                        new
                        {
                            Id = new Guid("e0740b9a-019d-45e9-bac6-3b969afee707"),
                            Address = "Mumbai",
                            Name = "Ritika Patel",
                            RollNo = 39
                        },
                        new
                        {
                            Id = new Guid("c8bd6769-f001-451d-8fb5-964a58155948"),
                            Address = "Pune",
                            Name = "Akhil Gupta",
                            RollNo = 40
                        },
                        new
                        {
                            Id = new Guid("7d37cdee-eef7-489b-99ce-e83ab5b67332"),
                            Address = "Nagpur",
                            Name = "Mehul Jain",
                            RollNo = 41
                        },
                        new
                        {
                            Id = new Guid("3f6a10d7-99e4-4a73-8cb1-76295850f9a8"),
                            Address = "Delhi",
                            Name = "Parul Sharma",
                            RollNo = 42
                        },
                        new
                        {
                            Id = new Guid("6c129cd9-390b-45cd-b722-bbdb72f8699f"),
                            Address = "Chennai",
                            Name = "Siddharth Thakur",
                            RollNo = 43
                        },
                        new
                        {
                            Id = new Guid("870e29c7-eebb-45a5-9584-bddd18453505"),
                            Address = "Mumbai",
                            Name = "Isha Gupta",
                            RollNo = 44
                        },
                        new
                        {
                            Id = new Guid("d294d84a-d023-4303-8ee7-c8abe1723563"),
                            Address = "Pune",
                            Name = "Tarun Kumar",
                            RollNo = 45
                        },
                        new
                        {
                            Id = new Guid("a52da703-185c-4f60-b35c-d8fceff4d5c4"),
                            Address = "Nagpur",
                            Name = "Kajal Verma",
                            RollNo = 46
                        },
                        new
                        {
                            Id = new Guid("cd040291-1d90-4077-b693-061d232870b7"),
                            Address = "Delhi",
                            Name = "Devika Reddy",
                            RollNo = 47
                        },
                        new
                        {
                            Id = new Guid("a96d2ed9-7fbd-4603-b536-3a6cc8632736"),
                            Address = "Chennai",
                            Name = "Rohit Pandey",
                            RollNo = 48
                        },
                        new
                        {
                            Id = new Guid("65354df2-c141-4592-9136-8afef1dd5425"),
                            Address = "Mumbai",
                            Name = "Harshita Singh",
                            RollNo = 49
                        },
                        new
                        {
                            Id = new Guid("9904381d-f48c-4e50-ad73-65f6123e368b"),
                            Address = "Pune",
                            Name = "Sandeep Raghav",
                            RollNo = 50
                        },
                        new
                        {
                            Id = new Guid("52429c67-d79d-4b02-9dfb-4bcd55316bfd"),
                            Address = "Nagpur",
                            Name = "Madhuri Gupta",
                            RollNo = 51
                        },
                        new
                        {
                            Id = new Guid("5ecfb4d1-ec5d-417a-a00a-f6cc7135cce4"),
                            Address = "Delhi",
                            Name = "Pranav Joshi",
                            RollNo = 52
                        },
                        new
                        {
                            Id = new Guid("8ea0cf98-39f8-458e-9957-7e1aa91b1e65"),
                            Address = "Chennai",
                            Name = "Gaurav Patil",
                            RollNo = 53
                        },
                        new
                        {
                            Id = new Guid("941cbb07-abd6-494a-af89-809dca93c679"),
                            Address = "Mumbai",
                            Name = "Sonali Verma",
                            RollNo = 54
                        },
                        new
                        {
                            Id = new Guid("7a85e196-ae09-44be-ba90-03d0fe9f0cbc"),
                            Address = "Pune",
                            Name = "Tushar Yadav",
                            RollNo = 55
                        },
                        new
                        {
                            Id = new Guid("d7e69f79-6745-40a0-b4f4-0ed6bb493661"),
                            Address = "Nagpur",
                            Name = "Pooja Mehta",
                            RollNo = 56
                        },
                        new
                        {
                            Id = new Guid("1ec05bdb-1216-42ab-b978-e29257ec0046"),
                            Address = "Delhi",
                            Name = "Vishal Kumar",
                            RollNo = 57
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
