// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pagination.Data;

#nullable disable

namespace Pagination.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pagination.Models.FileUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Pagination.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RollNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("643a830e-ace4-4478-ab3c-16339f392e2b"),
                            Address = "Nagpur",
                            Name = "Shyam Kumavat",
                            RollNo = 23
                        },
                        new
                        {
                            Id = new Guid("f1bd6b19-409b-4118-8007-fcfacca99e08"),
                            Address = "Mumbai",
                            Name = "Amit Kumar",
                            RollNo = 24
                        },
                        new
                        {
                            Id = new Guid("d7b809c7-09f8-41cb-bbcd-1c963cbd3e95"),
                            Address = "Pune",
                            Name = "Priya Verma",
                            RollNo = 25
                        },
                        new
                        {
                            Id = new Guid("c0d80227-f1e2-432b-86f5-1d44806147ad"),
                            Address = "Nagpur",
                            Name = "Neha Joshi",
                            RollNo = 26
                        },
                        new
                        {
                            Id = new Guid("a5368ddf-8d4c-47c7-aef2-d9d887a21311"),
                            Address = "Delhi",
                            Name = "Raj Patel",
                            RollNo = 27
                        },
                        new
                        {
                            Id = new Guid("bbdcd8ca-7641-4ec3-9fe8-f432370d827e"),
                            Address = "Chennai",
                            Name = "Ankit Singh",
                            RollNo = 28
                        },
                        new
                        {
                            Id = new Guid("9dcd3e2c-06b3-4b87-a521-ff0e9ffe98bd"),
                            Address = "Mumbai",
                            Name = "Ravi Sharma",
                            RollNo = 29
                        },
                        new
                        {
                            Id = new Guid("8b01f777-26c4-4df5-ab07-03164e140014"),
                            Address = "Pune",
                            Name = "Simran Kaur",
                            RollNo = 30
                        },
                        new
                        {
                            Id = new Guid("f2123783-087a-425c-862f-2ed81c41d7aa"),
                            Address = "Delhi",
                            Name = "Vikram Yadav",
                            RollNo = 31
                        },
                        new
                        {
                            Id = new Guid("da0d433a-f437-4904-a9f4-ed85348d298b"),
                            Address = "Nagpur",
                            Name = "Aarti Agarwal",
                            RollNo = 32
                        },
                        new
                        {
                            Id = new Guid("bcce2cb4-d19e-4c8a-a6a1-ae54a5a78d09"),
                            Address = "Chennai",
                            Name = "Manish Joshi",
                            RollNo = 33
                        },
                        new
                        {
                            Id = new Guid("06363eb2-4435-4ba5-be13-72eb6e396b1b"),
                            Address = "Mumbai",
                            Name = "Tanvi Mehta",
                            RollNo = 34
                        },
                        new
                        {
                            Id = new Guid("c7ee7156-e0b5-4ae8-a880-a234fa0fc09c"),
                            Address = "Pune",
                            Name = "Karan Deshmukh",
                            RollNo = 35
                        },
                        new
                        {
                            Id = new Guid("abd1e1b6-5deb-4f7f-9b93-4222bc4b297a"),
                            Address = "Nagpur",
                            Name = "Nikita Singh",
                            RollNo = 36
                        },
                        new
                        {
                            Id = new Guid("94076c78-9ff8-4523-9aec-820c3ac8cc98"),
                            Address = "Delhi",
                            Name = "Pradeep Kumar",
                            RollNo = 37
                        },
                        new
                        {
                            Id = new Guid("fee0917f-1dea-4d51-bfeb-8df35701681c"),
                            Address = "Chennai",
                            Name = "Sakshi Sharma",
                            RollNo = 38
                        },
                        new
                        {
                            Id = new Guid("6f0d268c-af69-4e41-8421-9535e3d68f63"),
                            Address = "Mumbai",
                            Name = "Ritika Patel",
                            RollNo = 39
                        },
                        new
                        {
                            Id = new Guid("6dbd23fa-feca-4667-a8d7-d5fee9c857f5"),
                            Address = "Pune",
                            Name = "Akhil Gupta",
                            RollNo = 40
                        },
                        new
                        {
                            Id = new Guid("7064b771-c12c-4513-9e90-61ab14e9fe56"),
                            Address = "Nagpur",
                            Name = "Mehul Jain",
                            RollNo = 41
                        },
                        new
                        {
                            Id = new Guid("00246a17-5b02-49bf-ba3c-3b0e20a7101e"),
                            Address = "Delhi",
                            Name = "Parul Sharma",
                            RollNo = 42
                        },
                        new
                        {
                            Id = new Guid("fa16ce44-4536-4f22-b6a1-1187dcf372d1"),
                            Address = "Chennai",
                            Name = "Siddharth Thakur",
                            RollNo = 43
                        },
                        new
                        {
                            Id = new Guid("00bbec68-f464-4fde-bfa1-07c1bba652fc"),
                            Address = "Mumbai",
                            Name = "Isha Gupta",
                            RollNo = 44
                        },
                        new
                        {
                            Id = new Guid("2ba4024a-5a17-4753-a1ce-11c0d17112af"),
                            Address = "Pune",
                            Name = "Tarun Kumar",
                            RollNo = 45
                        },
                        new
                        {
                            Id = new Guid("65e76dab-b52f-46f7-86d0-0ccd1f5cf0f5"),
                            Address = "Nagpur",
                            Name = "Kajal Verma",
                            RollNo = 46
                        },
                        new
                        {
                            Id = new Guid("d11ea3aa-7efb-4aaa-892e-0f5a9ea18d0f"),
                            Address = "Delhi",
                            Name = "Devika Reddy",
                            RollNo = 47
                        },
                        new
                        {
                            Id = new Guid("bcb136ab-c554-4cdb-b70f-03a5be592169"),
                            Address = "Chennai",
                            Name = "Rohit Pandey",
                            RollNo = 48
                        },
                        new
                        {
                            Id = new Guid("84808aae-e558-4cd8-b30f-104b3ca49d7b"),
                            Address = "Mumbai",
                            Name = "Harshita Singh",
                            RollNo = 49
                        },
                        new
                        {
                            Id = new Guid("78448499-3413-4dfb-888d-a30c5da8bdd5"),
                            Address = "Pune",
                            Name = "Sandeep Raghav",
                            RollNo = 50
                        },
                        new
                        {
                            Id = new Guid("79545054-3b9d-4a88-86a4-59ce71d3cbe1"),
                            Address = "Nagpur",
                            Name = "Madhuri Gupta",
                            RollNo = 51
                        },
                        new
                        {
                            Id = new Guid("3f0c7db6-a016-4792-91a5-bb2f7316d6d9"),
                            Address = "Delhi",
                            Name = "Pranav Joshi",
                            RollNo = 52
                        },
                        new
                        {
                            Id = new Guid("629909b7-5caf-4d08-b6b3-5b7569d759a9"),
                            Address = "Chennai",
                            Name = "Gaurav Patil",
                            RollNo = 53
                        },
                        new
                        {
                            Id = new Guid("9808dd8c-87e3-4817-a9b9-1c75490fc7a7"),
                            Address = "Mumbai",
                            Name = "Sonali Verma",
                            RollNo = 54
                        },
                        new
                        {
                            Id = new Guid("a25330a6-95a7-469b-8c34-4271d0ea353c"),
                            Address = "Pune",
                            Name = "Tushar Yadav",
                            RollNo = 55
                        },
                        new
                        {
                            Id = new Guid("e5d1adf2-b134-47e7-bf8c-c14b4671991b"),
                            Address = "Nagpur",
                            Name = "Pooja Mehta",
                            RollNo = 56
                        },
                        new
                        {
                            Id = new Guid("9e1973d4-959d-43c1-b9aa-9f19bf7215f3"),
                            Address = "Delhi",
                            Name = "Vishal Kumar",
                            RollNo = 57
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
